### ISSUE TITLE
Develop build infrastructure

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/cice5#1]
Develop spack based build infrastructure.

**Comment by aidanheerdegen** [comment]
[ParallelIO (PIO)](https://github.com/NCAR/ParallelIO) is a significant dependency for CICE. It is already supported by spack.

The spack package file for PIO is a useful source of information for configuring other CMake based spack builds 

https://github.com/spack/spack/blob/60997a7bc34616406e331a2919deec0bd36893a3/var/spack/repos/builtin/packages/parallelio/package.py

specifically regarding configuring options and passing information through to the CMake build. It also uses MPI, so the MPI dependency details are useful too.

**Comment by harshula** [comment]
PR: https://github.com/ACCESS-NRI/spack_packages/pull/8

**Comment by harshula** [comment]
Minimal changes required to cice5: https://github.com/ACCESS-NRI/cice5/pull/5

**Comment by harshula** [comment]
To compile with GCC, we need the following fix to the cice5 source package: https://github.com/ACCESS-NRI/cice5/issues/6
