### ISSUE TITLE
Model Documentation

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/cice5#13]
In the process of updating the ACCESS-OM2 model run instructions it [became apparent that we should make an effort to identify some good (authoritative?) documentation for the model components ](https://github.com/ACCESS-NRI/access-hive.org.au/pull/653#discussion_r1525753331).

The documentation could be a website, or a PDF or similar document. We should assess the likely longevity of the source and make a decision if we need to make a copy and host it ourselves.

It is also likely that the documentation would need updating. We shouldn't let that process stop us from recommending the documentation as-is: we can note caveats about what is covered in the documentation, and what might be missing.

This issue has been created to try and make sure this process does happen.

**Comment by anton-seaice** [comment]
I have a copy of a CICE5.1 documentation pdf. It was presumably made from this: https://github.com/CICE-Consortium/CICE-svn-trunk/tree/main/cicedoc

As you said, I guess we can provide the pdf as-is, and caveat that many access-specific code changes were made over time, some of which are noted in the OM2 technical report.

**Comment by aidanheerdegen** [comment]
Is it the same as in https://github.com/ACCESS-NRI/cice5/tree/master/doc?

If it is newer we should grab the most up to date. 

I guess we should then just link to whatever version is in the docs folder.

**Comment by anton-seaice** [comment]
Oh I didn't see that. Yes its the same as that PDF.

I guess we can link to that in the README, with a note along the lines of _There is PDF documentation available for CICE 5.1.2, however some changes were made to this fork to support coupling with ACCESS-OM2 and CM2, Parallel IO, ERA5 Forcing, BGC modelling and for other updates. Some of these changes are described in the ACCESS-OM2 Technical Report._

**Comment by aidanheerdegen** [comment]
Feel free to make a PR for that change @anton-seaice
