### ISSUE TITLE
Add compilation CI to CICE5

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/cice5#4]
Add GitHub workflow compilation CI

**Comment by aidanheerdegen** [comment]
Current workflow requires adding CICE5 to the build-ci repo to make sure the dependencies are available

https://github.com/ACCESS-NRI/build-ci/issues/13

**Comment by Quartzer2** [comment]
Ah, I thought was the 2nd step but not needed straight away. Learning...

**Comment by CodeGat** [comment]
Closed - CI has been added by @Quartzer2
